version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: |
          mkdir ~/my_test_artifacts
          echo "This should point to root_artifact.md for commit ${CIRCLE_SHA1} via status event" > ~/my_test_artifacts/root_artifact.md
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: ~/my_test_artifacts
          destination: test_artifacts

  repodispatch:
    docker:
      - image: cimg/base:current-22.04
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          mkdir ~/my_test_artifacts
          echo "This should point to root_artifact.md for commit ${CIRCLE_SHA1} via repository_dispatch event" > ~/my_test_artifacts/root_artifact.md
      - run: |
          set -ex
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_PROJECT_USERNAME}/dispatches \
            -d '{"event_type":"circleci-artifacts-redirector-action"}'

workflows:
  default:
    jobs:
      - build:
          name: build
      - repodispatch:
          name: repodispatch
