name: 'Lint'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  yaml_lint:
    name: YAML
    steps:
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows
